### ISSUE TITLE
*in++;

### ISSUE THREAD

**Issue by sjaehn** [airwindows/airwindows#29]
Hi Chris,
first of all big compliments for your great plugin collection. I already follow you yt streams for a wile, if I can find time. Very educating.

Now my minor issue. But maybe I'm wrong. I was wondering that the process method code for (almost?) all your plugins contain the following block at the end of the `while` loop:
```
*in1++;
*in2++;
*out1++;
*out2++;
```
The de-referencer `*` is not required here as you don't assign anything to where `in1` (and the others) point to. My compiler complains about it ([-Wunused-value]). But I think (hope) that compilers ignore this de-referencing that isn't used and it finally doesn't cost any CPU time or memory. Anyway, I would go with `in1++;` (and the others) without `*`.

**Comment by airwindows** [comment]
These are parts of the code directly from the templates (I think in this case it'd be the VST code?)

I don't change stuff that's part of the template: I'm glad it's not failing to work, but I'm leaving it alone regardless as I didn't write that code. The platform designer had it that way, so I'm going to leave it consistent with how Apple or Steinberg wrote it when they wrote it :)

**Comment by sjaehn** [comment]
OK, nice to know && fine for me.
