### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by ech2** [airwindows/airwindows#3]
Hej Chris!

I was able to build your open-source plugins for Linux. They seem to be working with the Linux build of Reaper. 

Here is the repo with the project: [ech2/airwindows-ports](https://github.com/ech2/airwindows-ports). The template is mostly ready, but I’d need to move the compilation flags from your project as well.

Would love to see native builds of other not (yet) open sourced Airwindows plugins!

**Comment by airwindows** [comment]
This is wonderful! If it actually works on my virtual Linux install and makes sense, you may have helped me and my brother over our jam w.r.t. LinuxVST. If we can understand what you've done and it works, my next job is to make Linux builds of ALL the plugins that are VST, open source or not (they'll all end up open source eventually :) )

**Comment by ech2** [comment]
If other your plugins are as simple to build as those you open-sourced (i.e. no external and weird dependencies, just sources), the workflow to add them up to the build I made is as follows:

1. Create a subdir `PluginName` in `src`.
2. Put the plugin headers and sources to it.
3. Add line `add_airwindows_plugin(PluginName)` to the root `CMakeLists`.
4. Generate makefiles and compile.

Here is how it works.

`CMakeLists.txt` basically describes what sources needs to be compiled, as well as how that should be done. You can have many of these files There are build targets that are basically results of the compilation (an executable or a library). In my configuration I create a target for each subdirectory in `src`. It is done with the function `add_airwindows_plugin(PluginName)`, which registers the contents of the directory `src/PluginName` as target with name `PluginName`. The functions itself is defined in `Helpers.cmake` (included from the root) and does the following:

1. Enumerate all `.h` and `.cpp` files in the directory `scr/PluginName`.
2. Create a library target `PluginName` and sets the plugin sources together with the `.cpp` files from the VST SDK to be compiled for this target.
3. Add paths for VST SDK headers.
4. Removes the target name prefix. Without it the tool would create libraries with names like `libPluginName.so`, which is weird for VST.

There is also a `CMakeLists.txt` file in the `include/vstsdk` directory. It sets up the `VSTSDK_ROOT` and `VSTSDK_SOURCES` variables. They are used by the `add_airwindows_plugin` function.

Hope this clears things out. Please, don’t hesitate to write me in case of any problems. I’m eager to see the plugins working on Linux and will help with that.

**Comment by ech2** [comment]
Just added the GrooveWear to the Linux build. Also added the `-O2` optimization flag, as in the Visual Studio project of yours.

**Comment by re23071998** [comment]
I need HighImpact for linux please!! :D
