### ISSUE TITLE
Bugfix Infinity2 algorithm

### ISSUE THREAD

**Issue by sjaehn** [airwindows/airwindows#30]
In the block
https://github.com/airwindows/airwindows/blob/master/plugins/MacAU/Infinity2/Infinity2.cpp#L263-L277 (and the respective lines in the VSTs) the lines 263 and 271 are the same. I think it should be `K = tan(M_PI * biquadB[0]);` for the line 271. Makes sense (at least for me) and sounds much better. I think it was simply a typo?

**Comment by sjaehn** [comment]
... and the same in Infity1.

**Comment by airwindows** [comment]
Well spotted! However:
biquadC[0] = biquadB[0] = biquadA[0] = ((pow(GetParameter( kParam_One ),2)*9900.0)+100.0) / GetSampleRate();

It's functionally the same. But well spotted! Even though they are the same number, they might not have been. Good eye :)

**Comment by sjaehn** [comment]
Yes, you are right. They are the same. There shouldn't be an audible difference. Hmmm. I don't trust my ears anymore ;-).

Anyway, if all three `biquadX[0]` values are the same, then K only needs to be calculated once. And two of those expensive `tan` can be removed. I'll try. It shouldn't make a big difference on systems with a big buffer size. But for those with a small one. And I have to run it inside my effect sequencer with `inFramesToProcess = 1`. This was the reason why I stumbled on it.
