### ISSUE TITLE
Mojo cpu use very high in M1 Rosetta in Renoise vs Reaper in both modes

### ISSUE THREAD

**Issue by Mr-Negative** [airwindows/airwindows#34]
First of all i'm big fan and big thank you for everything you are doing.

So i've changed my laptop to 2020 m1 mac from macbook 2012 model, and i've loaded todays some old projects in Renoise in Rosetta Mode, and i found it weird that all projects that was using mojo started crackling. It was not issue of buffer, it didnt helped a lot. By adding one mojo CPU looking into system activity monitor cpu usage jumped from 10% to 57% from the start if dissabled autosuspension on silence_.  Few other of yours i'm using have way less impact, but i do understand that there is no direct compare.
Output thermal plugin, what is multiband distortion, waveshaper /saturator it uses about 7% to compare
In Reaper-arm mojo about 9%. 
Is there reason and some math used in this that is very hard on Rosetta? is there possibility to some optimalisation or cutting something and making something slightly lighter?

(Renoise have pretty much fully functional demo, without ability to render to wav)

Edit: toTape 5 has 30% its okey, but toTape6 is 99%, on previous intel old mac 2012 it didnt have so much problem

**Comment by airwindows** [comment]
If you have the M1 processor, you should be using the signed versions of the plugins:
	https://www.airwindows.com/wp-content/uploads/SignedMacAUs.dmg
	https://www.airwindows.com/wp-content/uploads/SignedMacVSTs.dmg
	https://www.mediafire.com/folder/kua5r9x27mwrk/Plugins_Backup

The plugins are native to M1 and you shouldn't be using Rosetta with them, or trying to use them in non-M1 DAWs (such as current Renoise) unless you're OK with unpredictable performance. Hosting native stuff in a Rosetta host app is very unpredictable, and there's nothing more that I can do: I've already ported every plugin here to M1.

I hope you're able to work with enough plugins that you need: I own Renoise too, and like it a lot. I'm just not trying to use it on my M1 laptop :)

**Comment by Mr-Negative** [comment]
I jump between between Renoise  (rosetta) and Reaper(arm) but i didnt have any problems with other plugins using Rosetta, only Yours. Maybe double float is hard for m1 transcoding lol. But yeah on some point i will move complettly, and yeah those signed versions perform great and i love them. I only decided to ask, i do understand decision (to not experiment with rosetta more) completly. Growing pains of moving forward. Thank you.

**Comment by airwindows** [comment]
It's more that there's nothing I can actually do: I can only port the plugins to M1, or not, or make them fat binaries with both M1 and Intel code. I've done the latter, but when the hosting program runs into issues that way (I wish they could select whichever architecture works best, but it seems some of them send every sample through some kind of Rosetta layer regardless of whether a matching binary is present) then the only thing I can do is provide the ultimate destination architecture, and hope.

My hope is that providiing the M1 versions will eventually help as people catch up. It was a lot of work, but it's easier now that I can just add the porting to my weekly routine and do them one at a time :)

**Comment by Mr-Negative** [comment]
I just want to add for anybody who would read it, that last changes and cleanup made a huge difference in rosetta2 mode, its now perfect.
