### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by GabrielDougherty** [airwindows/airwindows#40]
Hi, when I visit your website https://www.airwindows.com/ my browser tries to download the page instead of displaying it. I can reproduce this problem in Safari and Brave Browser. I think your MIME type on your website is misconfigured. For example here is how to fix it if you use .htaccess files: https://stackoverflow.com/questions/28006188/browsers-try-to-download-html-file-instead-of-opening

**Comment by magnetophon** [comment]
Same her, using qutebrowser on linux.

**Comment by GabrielDougherty** [comment]
Looks fixed now.
