### ISSUE TITLE
Dubly3 has same VST id on Linux as Dubly2

### ISSUE THREAD

**Issue by xard-dev** [airwindows/airwindows#53]
Ardour 8.8 on Ubuntu 20.22 Linux refused to detect the Dubly3 as it had same VST id as Dubly2.

Checked the code and sure enough, both plugins seem to have the same id:
```
const unsigned long kUniqueId = 'dblz'; 
```

**Comment by airwindows** [comment]
Well spotted! That one got by me fair and square. The AU has used the ID 'dblx' (normally I increment the last letter but it was already Z for 2) but the VSTs have not adopted the correct ID. I will have an update by the next time I'm releasing an audio-type plugin, most likely next weekend not this weekend :)
