### ISSUE TITLE
Compresaturator2 refuses to load on Linux due to "symbol lookup error"

### ISSUE THREAD

**Issue by xard-dev** [airwindows/airwindows#54]
Compresaturator2 plugin on Ardour 8.8 on Ubuntu 20.22 Linux refuses to load because of following error:
```
symbol lookup error: /usr/local/lib/vst/airwindows-lxvst/Compresaturator2.so: undefined symbol: _Z20createEffectInstancePFlP7AEffectiilPvfE
Scan Failed.
```

I checked through this code repository and there does not seem to be code for Compresaturator2 here, so I can't look the source for possible clues.

**Comment by airwindows** [comment]
That's not supposed to be there: it's not in the non-Linux collections, and isn't in the CMAKE for current builds. I've removed it from the Linux collections, thanks for spotting that was there :)
