### ISSUE TITLE
Revise documentation for VST2 SDK

### ISSUE THREAD

**Issue by zonaj** [airwindows/airwindows#57]
The current VST 3 SDK from Steinberg no longer contains the VST2 SDK. As such, the current documentation is misleading.
I have attempted to build the plugins on the linux platform with the proper VST2 SDK files but these do not come with the CMakeLists.txt that the documentation suggests should exist. If there is a version of VST3 SDK that has a CMakeLists.txt *and* the vst2 sdk, I have failed to find it. Is there a specific VST 3 SDK version that satisfies all of this? My only recourse at this point is to try to fashion my own include/vstsdk/CMakeLists.txt (If it is bespoke, it would be nice to add to the repository).

**Comment by airwindows** [comment]
I'm not free to solve this under Steinberg's licensing rules. I'm allowed to ship VST2 plugins, but not to incorporate the VST2 SDK. I'm allowed to release open source VST3s noncommercially without signing off on the commercial VST3 license, but doing so would remove my right to make VST2s. And new programmers have no path to being able to legally make VST2s, now.

So I'm going to close this as unsolvable. I have no path to resolving this in any way, other than to support CLAP format plugins in future work (which I'm doing for the Pamplejuce-based stuff). I would be more sorry except it ain't in any way my fault and I've done the best I can: including warning you that if you're not a licensed VST2 maker in good standing, it might not be safe for you to even make VST2s as a new programmer. And that violates my principles as far as supporting legacy computers and DAWs, so I'm offended on your behalf. I think you should have better support over this, but it's not mine to give :)
